// This file has been generated by Specta. Do not edit this file manually.
/**  Chat（前端 Chat，对应 §3 数据模型） */
export type Chat = {
	id: string,
	title: string,
	createdAt: number,
	updatedAt: number,
};

/**  Favorite（前端 Favorite，对应 §3 数据模型） */
export type Favorite = {
	id: string,
	title: string,
	content: string,
	/**  来源 Chat id；手动创建时为 None */
	sourceChatId: string | null,
	/**  来源 Message id；手动创建时为 None */
	sourceMessageId: string | null,
	createdAt: number,
	updatedAt: number,
};

/**  `update_favorite` 的 patch 入参（前端 camelCase） */
export type FavoritePatch = {
	title: string | null,
	content: string | null,
};

/**  Message（前端 Message，对应 §3 数据模型） */
export type Message = {
	id: string,
	chatId: string,
	role: MessageRole,
	content: string,
	createdAt: number,
};

export type MessageRole = "user" | "assistant" | "system";

export type SendMessageResult = {
	userMessage: Message,
};

/**  Settings（前端 Settings，对应 §3 数据模型） */
export type Settings = {
	deepseekApiKey: string,
	/**  由 `deepseek_api_key` 非空派生，前端便捷字段 */
	hasApiKey: boolean,
};
