// This file has been generated by Specta. Do not edit this file manually.
/**  Chat（前端 Chat，对应 §3 数据模型） */
export type Chat = {
	id: string,
	title: string,
	roleId: string,
	createdAt: number,
	updatedAt: number,
};

/**  Favorite（前端 Favorite，对应 §3 数据模型） */
export type Favorite = {
	id: string,
	title: string,
	content: string,
	/**  来源 Chat id；手动创建时为 None */
	sourceChatId: string | null,
	/**  来源 Message id；手动创建时为 None */
	sourceMessageId: string | null,
	createdAt: number,
	updatedAt: number,
};

/**  `update_favorite` 的 patch 入参（前端 camelCase） */
export type FavoritePatch = {
	title: string | null,
	content: string | null,
};

/**  Message（前端 Message，对应 §3 数据模型） */
export type Message = {
	id: string,
	chatId: string,
	role: MessageRole,
	content: string,
	createdAt: number,
};

export type MessageRole = "user" | "assistant" | "system";

/**  Role（前端 Role，对应 §3 数据模型） */
export type Role = {
	id: string,
	name: string,
	responsibility: string,
	isBuiltin: boolean,
	createdAt: number,
	updatedAt: number,
};

export type SendMessageResult = {
	userMessage: Message,
};

/**  Settings（前端 Settings，对应 §3 数据模型） */
export type Settings = {
	deepseekApiKey: string,
	/**  由 `deepseek_api_key` 非空派生，前端便捷字段 */
	hasApiKey: boolean,
};

/**
 *  TreeNode（思维树图节点，对应 tree_nodes 表）
 * 
 *  与 `Chat` 通过相同 `id` 共存：
 *  - `tree_nodes.id` == `chats.id`（保持 `messages.chat_id` 关联正常）
 *  - `parent_id = NULL` 表示根节点（对应原 chats 表中的对话）
 *  - `role_id` 不可为空，默认绑定「默认助手」
 */
export type TreeNode = {
	id: string,
	title: string,
	/**  父节点 id；`None` 表示根节点 */
	parentId: string | null,
	/**  同级排序序号 */
	order: number,
	roleId: string,
	createdAt: number,
	updatedAt: number,
};

/**  带子节点数的 TreeNode（用于前端展示「N 个子节点」） */
export type TreeNodeWithChildren = {
	id: string,
	title: string,
	parentId: string | null,
	order: number,
	roleId: string,
	createdAt: number,
	updatedAt: number,
	/**  子节点数量（COUNT 子查询得到） */
	childCount: number,
};
